=== 13MasyA13/currency-aggregation-service/src/files/bank-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://www.w3schools.com/Banks"
           elementFormDefault="qualified"
           xmlns="/home/masya/Programming/Projects/Java/currency-aggregation-service/src/files/bank-schema.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="banks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="currency" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="currencyCode" type="xs:string"></xs:element>
                            <xs:element name="buy" type="xs:double"></xs:element>
                            <xs:element name="sell" type="xs:double"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 13MasyA13/currency-aggregation-service/src/files/AlfaBank.xml
<?xml version="1.0" encoding="UTF-8" ?>

<banks xmlns="http://www.w3schools.com/Banks"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.w3schools.com/Banks bank-schema.xsd">

    <currency>
        <currencyCode>USD</currencyCode>
        <buy>27.9</buy>
        <sell>28.3</sell>
    </currency>

    <currency>
        <currencyCode>EUR</currencyCode>
        <buy>31.9</buy>
        <sell>32.5</sell>
    </currency>

</banks>
